import { Router } from 'express';
import { adminController } from './admin.controller';
import { authenticate, requireAdmin } from '../../shared/middleware';
const router = Router();
router.get('/public-config', adminController.publicConfig);
router.post('/contact', adminController.contact);
router.get('/public-posts', adminController.publicPosts);
router.get('/contacts', authenticate, requireAdmin, adminController.contacts);
router.get('/posts', authenticate, requireAdmin, adminController.posts);
router.put('/posts', authenticate, requireAdmin, adminController.savePost);
router.put('/config', authenticate, requireAdmin, adminController.saveConfig);
router.get('/notifications', authenticate, adminController.notifications);
router.get('/subscriptions', authenticate, adminController.subscriptions);
router.post('/notifications', authenticate, requireAdmin, adminController.sendNotification);
router.post('/payments/start', authenticate, adminController.startPayment);
router.post('/payments/callback', adminController.paymentCallback);
router.get('/payments/callback', adminController.paymentCallback);
router.post('/payments/ipn', adminController.paymentIpn);
router.get('/payments/ipn', adminController.paymentIpn);
export default router;
