import { useEffect, useState } from 'react';
import { siteApi } from '@/api/site.api';
import toast from 'react-hot-toast';

export default function AdminPage() {
  const [tab, setTab] = useState('Config'); const [config, setConfig] = useState<any>({ title: '', logo: '', subtitle: '', content: {} });
  const [contentText, setContentText] = useState('{}');
  const [posts, setPosts] = useState<any[]>([]); const [contacts, setContacts] = useState<any[]>([]);
  const [post, setPost] = useState<{ id?: string; title: string; slug: string; excerpt: string; content: string; published: boolean }>({ title: '', slug: '', excerpt: '', content: '', published: false });
  const [notice, setNotice] = useState({ title: '', message: '', targetUserId: '' });
  useEffect(() => { siteApi.config().then((value) => { setConfig(value); setContentText(JSON.stringify(value.content ?? {}, null, 2)); }).catch(() => { }); siteApi.posts().then(setPosts).catch(() => { }); siteApi.contacts().then(setContacts).catch(() => { }); }, []);
  const saveConfig = async () => { try { const nextConfig = { ...config, content: JSON.parse(contentText) }; await siteApi.saveConfig(nextConfig); setConfig(nextConfig); toast.success('Website content saved'); } catch { toast.error('Public page content must be valid JSON'); } };
  const savePost = async () => { const saved = await siteApi.savePost(post); setPosts((current) => post.id ? current.map((p) => (p._id ?? p.id) === post.id ? saved : p) : [saved, ...current]); setPost({ title: '', slug: '', excerpt: '', content: '', published: false }); toast.success('Post saved'); };
  const send = async () => { await siteApi.sendNotification(notice); setNotice({ title: '', message: '', targetUserId: '' }); toast.success('Notification sent'); };
  return <div className="max-w-5xl mx-auto p-6 md:p-10"><h1 className="text-3xl font-bold mb-6">Admin panel</h1><div className="flex gap-2 mb-6">{['Config', 'Blog', 'Contact messages', 'Notifications'].map((x) => <button key={x} onClick={() => setTab(x)} className={`px-4 py-2 rounded-xl ${tab === x ? 'bg-terra text-white' : 'bg-white'}`}>{x}</button>)}</div>
    {tab === 'Config' && <section className="bg-white p-6 rounded-2xl space-y-3"><h2 className="text-xl font-bold">Website configuration</h2>{['title', 'logo', 'subtitle'].map((field) => <label key={field} className="block capitalize">{field}<input className="input w-full" value={config[field] ?? ''} onChange={(e) => setConfig({ ...config, [field]: e.target.value })} /></label>)}<label className="block">Public page content (JSON)<textarea className="input w-full" rows={8} value={contentText} onChange={(e) => setContentText(e.target.value)} /></label><button className="btn-primary" onClick={saveConfig}>Save configuration</button></section>}
    {tab === 'Blog' && <section className="bg-white p-6 rounded-2xl space-y-3"><h2 className="text-xl font-bold">{post.id ? 'Edit blog post' : 'Create blog post'}</h2>{(['title', 'slug', 'excerpt', 'content'] as const).map((field) => <input key={field} placeholder={field} className="input w-full" value={post[field]} onChange={(e) => setPost({ ...post, [field]: e.target.value })} />)}<label><input type="checkbox" checked={post.published} onChange={(e) => setPost({ ...post, published: e.target.checked })} /> Published</label><button className="btn-primary block" onClick={savePost}>Save post</button><ul>{posts.map((p) => <li key={p._id ?? p.id} className="border-t py-3 flex justify-between">{p.title} · {p.published ? 'Published' : 'Draft'}<button className="text-terra" onClick={() => setPost({ id: p._id ?? p.id, title: p.title, slug: p.slug, excerpt: p.excerpt ?? '', content: p.content, published: p.published })}>Edit</button></li>)}</ul></section>}
    {tab === 'Contact messages' && <section className="bg-white p-6 rounded-2xl"><h2 className="text-xl font-bold mb-4">Contact messages</h2>{contacts.map((c) => <article key={c._id ?? c.id} className="border-b py-4"><b>{c.name}</b> · {c.email}<p>{c.message}</p></article>)}</section>}
    {tab === 'Notifications' && <section className="bg-white p-6 rounded-2xl space-y-3"><h2 className="text-xl font-bold">Send notification</h2><input className="input w-full" placeholder="Title" value={notice.title} onChange={(e) => setNotice({ ...notice, title: e.target.value })} /><textarea className="input w-full" placeholder="Message" value={notice.message} onChange={(e) => setNotice({ ...notice, message: e.target.value })} /><input className="input w-full" placeholder="User ID (blank sends to everyone)" value={notice.targetUserId} onChange={(e) => setNotice({ ...notice, targetUserId: e.target.value })} /><button className="btn-primary" onClick={send}>Send notification</button></section>}
  </div>;
}
